on:
  release:
    types: [created]

jobs:
  build:
    name: Build ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Windows Latest",
            os: windows-latest,
            target: x86_64-pc-windows-msvc
          }
        - {
            name: "Ubuntu Latest",
            os: ubuntu-latest,
            target: x86_64-unknown-linux-gnu
          }
        - {
            name: "MacOS Latest",
            os: macos-latest,
            target: x86_64-apple-darwin
          }
    steps:
    - uses: actions/checkout@v3
    - name: Install stable
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.config.target }}
    - name: Build wheat
      run: cargo build --profile release-lto
    - name: Run tests
      run: cargo test --profile release-lto
    - name: Prepare build artifact for upload (Windows)
      if: ${{ runner.os == 'Windows' }}
      run: |
        mkdir build\release-lto
        copy target/release-lto/*.dll build\release-lto
        copy target/release-lto/wheat.exe build\release-lto
        copy target/release-lto/wheat.pdb build\release-lto
    - name: Prepare build artifact for upload (Linux)
      if: ${{ runner.os == 'Linux' }}
      run: |
        mkdir -p build/release-lto
        cp target/release-lto/libSDL*.so build/release-lto
        cp target/release-lto/wheat build/release-lto
    - name: Prepare build artifact for upload (MacOS)
      if: ${{ runner.os == 'macOS' }}
      run: |
        mkdir -p build/release-lto
        cp target/release-lto/wheat* build/release-lto
        cp target/release-lto/*SDL* build/release-lto
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        path: build/release-lto
        name: wheat-${{ matrix.config.target }}-${{ github.ref_name }}
  
  release:
    needs: build
    if: success()
    name: Create release (${{ matrix.config.os }})
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            os: windows-latest,
            target: x86_64-pc-windows-msvc
          }
        - {
            os: ubuntu-latest,
            target: x86_64-unknown-linux-gnu
          }
        - {
            os: macos-latest,
            target: x86_64-apple-darwin
          }
    steps:
    - name: Download artifact
      uses: actions/download-artifact@4
      with:
        name: wheat-${{ matrix.target }}-${{ github.ref_name }}
        path: release-artifact
    - name: Generate checksum
      uses: jmgilman/actions-generate-checksum@v1
      with:
        patterns: |
          release-artifact/*.zip
          release-artifact/*.tar.gz
    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          checksum.txt
          release-artifact/*.zip
          release-artifact/*.tar.gz
